# Generated by Django 4.2.1 on 2023-12-30 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Advitya_app', '0003_remove_useractivityregistration_name_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivityregistration',
            name='name_user',
            field=models.CharField(default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Activity 1', 'Activity 1'), ('Activity 2', 'Activity 2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useractivityregistration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
