# Generated by Django 4.2.1 on 2023-12-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advitya_app', '0004_useractivityregistration_name_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivityregistration',
            name='name_user',
        ),
    ]
