# Generated by Django 4.2.1 on 2024-01-01 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Advitya_app', '0006_userprofile_delete_socio_trivia_reg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio_trivia_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='useractivityregistration',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='useractivityregistration',
            name='name_user',
            field=models.CharField(default='no', max_length=50),
        ),
        migrations.AddField(
            model_name='useractivityregistration',
            name='phone_number',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Activity 1', 'Activity 1'), ('Activity 2', 'Activity 2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useractivityregistration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
