# Generated by Django 4.2.1 on 2024-01-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advitya_app', '0007_socio_trivia_reg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivityregistration',
            name='name_user',
        ),
    ]
