# Generated by Django 4.2.1 on 2024-01-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advitya_app', '0008_remove_useractivityregistration_name_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivityregistration',
            name='name_user',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
