# Generated by Django 4.2.1 on 2024-01-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advitya_app', '0009_useractivityregistration_name_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivityregistration',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
