# Generated by Django 4.2.1 on 2024-01-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advitya_app', '0010_useractivityregistration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivityregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
