# Generated by Django 4.2.1 on 2024-01-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advitya_app', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
