# Generated by Django 4.2.1 on 2024-01-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advitya_app', '0016_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='referral',
        ),
    ]
