# Generated by Django 4.2.1 on 2024-01-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advitya_app', '0019_rename_state_useraccount_events_activityregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='events',
            field=models.CharField(default='', max_length=100),
        ),
    ]
