# Generated by Django 4.2.1 on 2024-01-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advitya_app', '0020_alter_useraccount_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='events',
            field=models.TextField(default=''),
        ),
    ]
